# Generated by Django 5.1.2 on 2024-11-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_category_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='basic_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
    ]
